RESULT_SQL=""
for LOOP_DB_NAME in $(echo $MYSQL_DRUPAL_DATABASES | sed "s/,/ /g")
do    
    #https://www.drupal.org/docs/7/system-requirements/database-server
    RESULT_SQL+="CREATE DATABASE $LOOP_DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci;"
    RESULT_SQL+="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON $LOOP_DB_NAME.* TO '$MYSQL_DRUPAL_USER_NAME'@'172.20.%' IDENTIFIED BY '$MYSQL_DRUPAL_USER_PASSWORD';"
done
mysql -u root -p$MYSQL_ROOT_PASSWORD <<< $RESULT_SQL